### ISSUE TITLE
Object doesn't support property or method 'values'

### ISSUE THREAD

**Issue by KennedyTedesco** [null-null-null/ember-keyboard#19]
Hi, I'm having this issue on IE11:

![image](https://cloud.githubusercontent.com/assets/999232/11824981/cd073f8a-a363-11e5-8653-90b285479644.png)

Do you have any idea to fix it?

Cheers!

**Comment by null-null-null** [comment]
I'm working on an overhaul that should fix this. Until then, you should be able to get this working by adding this to you `ember-cli-build.js`:

```js
new EmberApp({
  babel: {
    includePolyfill: true
  }
})
```

**Comment by KennedyTedesco** [comment]
Awesome! Thank you so much.

**Comment by null-null-null** [comment]
Just fyi, the latest version of ember-keyboard (0.2.2) no longer requires the babel polyfill. Thanks for reminding me that this is an issue!

**Comment by KennedyTedesco** [comment]
Thanks for your time on this.. :+1:
