### ISSUE TITLE
Test helpers

### ISSUE THREAD

**Issue by lolmaus** [null-null-null/ember-keyboard#20]
How do I test `ember-keyboard`-driven events?

**Comment by null-null-null** [comment]
You should be able to use Ember's baked-in test helpers. For unmodified key events, try [keyEvent](http://emberjs.com/api/classes/Ember.Test.html#method_keyEvent). If you want a modified key event (eg, +shift, +meta, +ctrl), try using [triggerEvent](http://emberjs.com/api/classes/Ember.Test.html#method_triggerEvent) (there's a good example of it [here](https://github.com/null-null-null/ember-keyboard/blob/master/tests/acceptance/ember-keyboard-test.js#L67)). Let me know if that works for you!

**Comment by lolmaus** [comment]
Thank you for the modifier example! The only thing that's missing now is support for component integration tests: `keyEvent` and `triggerEvent` aren't available there.

**Comment by null-null-null** [comment]
I haven't tested this yet, but you should be able to accomplish that with [jQuery key events](https://api.jquery.com/category/events/keyboard-events/). If you're interested in making some helpers that do that, it should be a pretty straightforward job. I'd be happy to merge in a feature like that.

**Comment by lolmaus** [comment]
Thank you Timothy, I'll look into it next time I need key events in tests.

**Comment by null-null-null** [comment]
Let me know if https://github.com/null-null-null/ember-keyboard/commit/922e2fbe158f0296ff98f8b1a4c72d49686a979f works for you! It adds a `getKeyCode`, which you can then use with `keyEvent` like so:

```js
import { getKeyCode } from 'ember-keyboard';

. . . .

keyEvent(document, 'keydown', getKeyCode('a'));
keyEvent(document, 'keydown', getKeyCode('ArrowRight'));
keyEvent(document, 'keydown', getKeyCode('Backspace'));
keyEvent(document, 'keydown', getKeyCode(' '));
```

**Comment by lolmaus** [comment]
I was thinking of helpers like `keyDown`, `keyUp` and `keyPress`, all of which would have a footprint like this:

```js
keyDown(target, 'ArrowRight');
```

**Comment by null-null-null** [comment]
Since `ember-keyboard`'s listeners are set on the `document`, we might not even need to provide a `target`, leading to `keyDown('ArrowRight')`. Would also be nice to support modifier keys, which are currently kind of tricky, eg: `keyDown('ctrl+ArrowRight')`.

**Comment by lolmaus** [comment]
That's the level of convenience one would expect from custom test helpers!

**Comment by null-null-null** [comment]
Resolved by https://github.com/null-null-null/ember-keyboard/commit/d384eba557682aecb9bd6d68f967978a1c6608b2. Enjoy! And thanks for the idea.

**Comment by lolmaus** [comment]
Thank you!

Did you decide not to implement modifiers? Also, this needs a readme update.

**Comment by null-null-null** [comment]
It should support modifiers. I've got `keyDown('ArrowRight+ctrl+shift')` working in the tests. Let me know if they're not working for you!

Also, just updated gh-pages to reflect these changes. You should see documentation in the interactive demo now.

**Comment by lolmaus** [comment]
You rock! :metal: 

I will try them out next time I do something keyboard-related.
