### ISSUE TITLE
Uncaught TypeError: t[m] is not a function

### ISSUE THREAD

**Issue by dipayanb** [null-null-null/ember-keyboard#21]
I am getting this strange error with the following code :
```javascript
export default Ember.Component.extend(EKMixin, {
 
  activateKeyboard: Ember.on('init', function() {
    this.set('keyboardActivated', true);
  }),

  resetAllSelection: Ember.on(keyUp('Escape'), function() {
    this.sendAction('resetSelection');
  }),

  /* TODO: Fix this code. to select all using keyboard */
  selectAll: Ember.on(keyUp('shift+s'), function() {
    this.sendAction('selectAll', false);
  })
});
```
The screen shot is given below:
<img width="1920" alt="screen shot 2016-01-21 at 12 06 26 am" src="https://cloud.githubusercontent.com/assets/2174097/12459127/296ed126-bfd3-11e5-99bb-d4da32244985.png">
The 'Escape' works fine but it is throwing this error when 'shift+s' is pressed.

**Comment by dipayanb** [comment]
Sorry there was a mistake in the code and hence ember was throwing the error. Closing it.

**Comment by null-null-null** [comment]
:+1:
