### ISSUE TITLE
Default config read error: Cannot read property 'listeners' of undefined

### ISSUE THREAD

**Issue by deanmraz** [null-null-null/ember-keyboard#26]
Confirmed on ember 2.3 and 2.4

By default it should be expected to listen to: ['keyUp', 'keyDown', 'keyPress'], but without emberKeyboard defined in config. 

This is the error I get when trying to use defaults: 
```
keyboard.js:54 Uncaught TypeError: Cannot read property 'listeners' of undefined
var listeners = _emberGetConfig['default'].emberKeyboard.listeners || ['keyUp', 'keyDown', 'keyPress'];
```

Should check to see if key "emberKeyboard" exists before access listeners.

**Comment by null-null-null** [comment]
Good catch! Should be resolved by https://github.com/null-null-null/ember-keyboard/commit/a10daf78e0713197af7683d8002ad91b2e59d0cb. The fix should be on NPM as 1.0.2 in a few minutes.

**Comment by null-null-null** [comment]
The issue should be resolved. Let me know if you continue to experience it!

**Comment by deanmraz** [comment]
@null-null-null confirmed, thanks!
