### ISSUE TITLE
Edge support

### ISSUE THREAD

**Issue by mschinis** [null-null-null/ember-keyboard#27]
Hello,

Both the demo and my site don't seem to work properly with Microsoft Edge. I don't see any errors in the console. Any ideas?

Best,
Michael

**Comment by mschinis** [comment]
The issue seems to be tied to the arrow keyboard buttons. Slash "/" works properly.

**Comment by null-null-null** [comment]
Thanks for looking into this. I don't currently have Edge, but I can get a windows computer in a couple of weeks to start figuring this out. Sorry it'll take awhile.

**Comment by mschinis** [comment]
Hm. I can reproduce it in IE 10-11 as well. Might be worth giving it a go on a trial account on browserstack :)

**Comment by null-null-null** [comment]
Should be resolved by https://github.com/null-null-null/ember-keyboard/commit/94e11c141e47b7b5694dc02a91861ac2c4e0a378. Thanks again for reporting this, @mschinis! And please let me know if you experience any continued issues with IE.

**Comment by mschinis** [comment]
Will give it a go tomorrow and report if there's any other issues. Thanks a
lot for the quick fix!
