### ISSUE TITLE
wider scope

### ISSUE THREAD

**Issue by Pasikonik** [null-null-null/ember-keyboard#28]
Is it possible to set this mixin in whole route instead single component?

**Comment by null-null-null** [comment]
I haven't tested it, but that should work. Just use the `EKMixin` as usual, and then add something like:

```js
  activateKeyboardWhenPresent: on('init', function() {
    set(this, 'keyboardActivated', true);
  })
```

Let me know if that works for you!

**Comment by null-null-null** [comment]
Any luck with this? You should be able to put that directly in your route.

**Comment by null-null-null** [comment]
Closing for the time being. Let me know if there is any further trouble with this, @Pasikonik.

**Comment by Pasikonik** [comment]
All work perfect, sorry for slow response.

**Comment by ryanjm** [comment]
@Pasikonik Thank you for the tip about `Ember.Evented`! That was the piece I was missing.

It would be helpful to have that in the docs for those of us wanting to include this in a controller for now.
