### ISSUE TITLE
Example in docs for modifier key combination should use keyDown

### ISSUE THREAD

**Issue by lukemelia** [null-null-null/ember-keyboard#29]
It seems that you need to use `keyDown` when using combinations such as `meta+Enter`. It took me a little while to realize this, and it would have helped if the example in the docs showed it this way.

**Comment by null-null-null** [comment]
I'm unable to duplicate this, at least on Ubuntu with Chrome and Firefox. `keyUp+modifier-key` has generally worked for me; the only caveat I've found is around `event.preventDefault`. The `keyUp` observer won't fire until after the event completes its default action, while `keyDown` will catch the event before it can complete.

I'd definitely like to figure out what's causing this, though. Mind sharing a failing example?

**Comment by lukemelia** [comment]
I did `ember new keyboard-example` and added a simple component with `meta+Enter` set up to fire on keyDown and keyUp. The functions add to a log that is displayed by the template. On Chrome Mac,  when pressing meta(Command)+Enter only the keyDown logs. It's at https://github.com/lukemelia/keyboard-example and the part that is not initial ember-cli app is added here: https://github.com/lukemelia/keyboard-example/commit/185ea7824dba35bc0105d41e5e944f754a0b490b

**Comment by null-null-null** [comment]
Looks like this is OS-related. On Ubuntu, I'm logging both the `keyDown` and `keyUp` events.

Either way, thanks for taking the time to report this! Not sure if there's a solution, but I'll start looking into one. Until then, I'll definitely add that warning to the docs.

**Comment by null-null-null** [comment]
Docs have been [updated](https://github.com/null-null-null/ember-keyboard/commit/95ab621a6f3d382dfb77fb60d686ef2ea4aac1d5). Thanks again, @lukemelia!

**Comment by lukemelia** [comment]
Looks good! 👍
