### ISSUE TITLE
Demo: ctrl+arrow key doesn't work

### ISSUE THREAD

**Issue by SirZach** [null-null-null/ember-keyboard#30]
Arrow keys and ctrl+shift+arrow works but ctrl+arrow does not work.

**Comment by null-null-null** [comment]
They work for me on Ubuntu Chrome, but this might be related https://github.com/null-null-null/ember-keyboard/issues/29. Which OS are you using? And browser?

**Comment by SirZach** [comment]
Chrome 50.0.2661.102  on Mac OS.

**Comment by null-null-null** [comment]
I'm gonna have to get my hands on a Mac and play around. Not sure what is going on this time.

**Comment by blimmer** [comment]
@SirZach I'm able to reproduce this. The problem is as follows:

When just the left arrow is pressed, these are the keys reported
```javascript
["ArrowLeft"]
```

But when you are holding control, this is reported:
```javascript
["ControlLeft", "ctrl"]
```

and with shift:
```javascript
["ArrowLeft", "ctrl", "shift"]
```

@null-null-null is this something we should normalize for the end user?

**Comment by null-null-null** [comment]
@blimmer Great find! No, on Ubuntu it's always ArrowLeft. And yes, we should definitely normalize this before 2.0. In 1.0 we were doing something [similar](https://github.com/null-null-null/ember-keyboard/blob/94e11c141e47b7b5694dc02a91861ac2c4e0a378/addon/utils/listener-name.js#L4) for alt key names in Windows. We could do something like that again, but I'd like to find a list somewhere of what else is being changed to "Control${keyName}".

**Comment by null-null-null** [comment]
@blimmer Actually, when you're getting "ControlLeft", is that in 2.0? Because "ControlLeft" should hopely be referring to the left control key: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code.

**Comment by blimmer** [comment]
Yep, that's in 2.0. I wonder if there's something weird about the OS grabbing and preventing Ctrl+Arrow.

**Comment by null-null-null** [comment]
I changed the interactive demo and added a warning against using `ctrl` modifiers due to MacOS swallowing the events. It might be worth compiling a list of key bindings that cannot be used on particular systems. I'll look into this today.
