### ISSUE TITLE
Use ember-keyboard on the application as a whole

### ISSUE THREAD

**Issue by SirZach** [null-null-null/ember-keyboard#31]
I want keyboard shortcuts to work without setting them to a specific component. I want the keyboard shortcut to trigger a page transition for example. Because there's isn't a application component, any thoughts on how to do this?

**Comment by null-null-null** [comment]
This isn't documented (though it could easily be added to the misc section at the end of the docs), but the `EKMixin` can be added to any Ember object, including a route. So, you should be able to just add these key bindings directly to your application route.

**Comment by SirZach** [comment]
Oooh good to know. I'll test that out and if it works I'll submit a PR for documentation.

**Comment by null-null-null** [comment]
Thanks, @SirZach!

**Comment by oliverwilkie** [comment]
If it helps, I've been able to get it to work on Routes, but not Controllers.
Thanks for the plugin!

**Comment by blimmer** [comment]
@SirZach do you have time for that PR? If so, it would be a nice addition to the 2.0.0 branch.

**Comment by null-null-null** [comment]
@oliverwilkie As of `2.1.1`, controllers can now use the EKMixin.

**Comment by monovertex** [comment]
I'm not sure if I'm doing something wrong, but when using the EKMixin in a service I get this error:

`Uncaught TypeError: responder.trigger is not a function`

I'm guessing services don't have that required `trigger` method defined?

**Comment by null-null-null** [comment]
@monovertex You should be able to fix that by upgrading to `ember-keyboard 2.1.1`. If that's not an option, you might also be able to just add the `Ember.Evented` mixin to your service.

**Comment by null-null-null** [comment]
Docs have been updated with this info. Thanks everyone!
