### ISSUE TITLE
TEXTAREA and INPUT unfocus issues

### ISSUE THREAD

**Issue by bladnman** [null-null-null/ember-keyboard#35]
I have a simple scenario where adding `{{textarea}}` or `{{input}}` helpers works as described in not producing Ember-Keyboard events, but after leaving the fields the events do not start to flow again. 

I have debugged and your `resignFirstResponderOnFocusOut` is firing as expected when I leave the field but no more Ember-Keyboard events are reported in other listeners.

As a quick fix I did the following: I changed your current blur code of:
```
resignFirstResponderOnFocusOut: on('focusOut', function() {
  set(this, 'keyboardFirstResponder', false);
})
```

to also deactivate the keyboard like this:
```
resignFirstResponderOnFocusOut: on('focusOut', function() {
  setProperties(this, {
	  keyboardActivated: false,
	  keyboardFirstResponder: false
  });
})
```

This seems to solve the issue. I'm not sure if you had a reason to keep the keyboard activated after blur, but your code seemed intentional.

It may be worth noting that I have no other first responders set, nor any priorities anywhere. I did try setting another component to also be a first responder (prior to the focus) but that did not help.

```
Ember  : 2.4.3
jQuery : 2.2.1
OSX / Chrome 51.0.2704.84 (64-bit)
```

**Comment by bladnman** [comment]
added a quick PR in case this seems reasonable

**Comment by null-null-null** [comment]
Sorry about the bug, @bladnman! I'm still trying to replicate the issue, but I'm not having any luck. (I'm using the inputs on the [demo](http://null-null-null.github.io/ember-keyboard/) to test.) Could you send me a repo with a failing example? I'd like to figure out why this works in some situations, but not all.

I can definitely see your PR working in 99% of cases, but it would lead to regressions for folks that want an input to be a responder in its own right. For instance, if they have a global search field that they want to focus whenever the 's' key is pressed. In those cases, setting `keyboardActivated` to false on the focusOut event would turn off that functionality.

**Comment by null-null-null** [comment]
Let me know if this problem presents itself again.
