### ISSUE TITLE
[FEATURE REQUEST] Easily wire up ⌘ + Key or Ctrl + Key based on OS

### ISSUE THREAD

**Issue by blimmer** [null-null-null/ember-keyboard#38]
Often, if you're implementing a Ctrl + Key type shortcut, you want that to be ⌘ + Key on macOS. Right now, I produce the events in a helper function after figuring out what OS the user is on.

What do you think about adding a special command we could issue that would do this for us? Something like:

```javascript
  _hotkeySubmit: on(keyDown('Enter+CtrlOrCommand'), function() {
    // do stuff
  }),
```

**Comment by null-null-null** [comment]
Just to be clear, should it work like this:

Mac:
true when `meta` is held
false when `ctrl`is held

Other platform:
false when `meta` is held
true when `ctrl` is held

(I'm not super-savvy with Macs, but it looks like ⌘ is mapped to `metaKey`. Do people typically call it the Command key, though? If so, which in your opinion would be less confusing, `ctrlOrMeta` or `ctrlOrCommand`?)

**Comment by null-null-null** [comment]
Actually, what if we just call it `cmd`? So, `keyDown('Enter+cmd')`, which does the above. `meta` for Macs, `ctrl` for other platforms.

**Comment by blimmer** [comment]
Your assumption in the first comment is correct. Typically when people are talking about the ⌘ they say the word "command" as that's what printed on the Mac keyboard. However, in the keyboard event world, it maps to `meta` (same with windows key on windows). `Enter+cmd` definitely works for me.

**Comment by null-null-null** [comment]
I'll bring that into 2.0
