### ISSUE TITLE
Key Indifference + `cmd`

### ISSUE THREAD

**Issue by blimmer** [null-null-null/ember-keyboard#40]
I ran into some weird behavior when trying to utilize Key Indifference with the `cmd` behavior:

I want to wire up a listener for `Digit1+cmd` through `Digit9+cmd`. I was hoping to use key indifference like this:
```javascript
_handler: on(keyDown('cmd'), function() {
  // get the number from the event and do stuff
});
```

However, that listener never fires. Looking at the key event that's coming in, this is the result:
```javascript
['OSRight', 'meta']
```

is this a bug?

**Comment by null-null-null** [comment]
That seems like the correct listener event, as it should actually be listening for 'cmd' here (just like it would be listening for 'Digit1' if you `keyDown('Digit1')`). To get this working, you'd do something like:

```js
_handler: on(keyDown(), function(event) {
  // get the number from the event and do stuff
});
```

But you'd also have to check the event to see if it 'cmd' is being held. Probably something like:

```js
_handler: on(keyDown(), function(event) {
  const cmdKey = `${getCmdKey()}Key`;
  if (event[cmdKey]) {
   // get the number from the event and do stuff
  }
});
```

Let me know if that works!

**Comment by blimmer** [comment]
That'll work! Just wanted to make sure that was the correct way to do it.

**Comment by dangodev** [comment]
Had a similar problem—this works for `keyDown()` but not for `keyUp()` on Chrome / Mac.
Weirdly enough, for Mac, `event.metaKey` is `true` on down, and `false` on up, even though it still returns the proper `keyCode`: `91`.

This is a little outside the scope of this issue, but would anybody happen to know if this is expected behavior, or a bug?
