### ISSUE TITLE
Component Integration Test Helpers

### ISSUE THREAD

**Issue by bargar** [null-null-null/ember-keyboard#43]
Acceptance test helpers seem to be in good shape thanks to resolution of #20. 

For tighter component-level testing, helpers that would work outside of acceptance tests would be greatly appreciated. 

Even a working example of triggering specific key events _without_ helpers in the context of a component integration test would be appreciated. I figure the basis of this could be something like
```
$(document).trigger('keyup', [ getKeyCode('KeyD') ]);
```
but I have had no luck getting this to work thus far.

**Comment by null-null-null** [comment]
Thanks for the idea! This should be resolved now, via https://github.com/null-null-null/ember-keyboard/commit/90e19546a477a5141a3412f5a8d480088f317801. You can now:

```js
import { triggerKeyDown, triggerKeyPress, triggerKeyUp } from 'ember-keyboard';

. . . .

triggerKeyDown('KeyA');
triggerKeyDown('KeyA+shift+cmd');
```

**Comment by bargar** [comment]
@null-null-null works like a charm. *tips cap in appreciation*
