### ISSUE TITLE
Not working on a controller

### ISSUE THREAD

**Issue by eibrahim** [null-null-null/ember-keyboard#45]
I got working in a component and a route but can't get it to work on a controller.  Is that by design?  Why?

**Comment by null-null-null** [comment]
Good catch. It's resolved by https://github.com/null-null-null/ember-keyboard/commit/3dffb64b2c4329f4087e41a9cba9a4d32e6d3d7a. Grab the bugfix on `2.1.1`.

**Comment by ryanjm** [comment]
@null-null-null How do I tell it to stop observing the key when the controller is no longer being displayed?

```
  editShortcut: Ember.on(keyUp('KeyE'), function() {
    this.transitionToRoute('myController.edit');
  }),
```

This transitions the route even when the controller isn't displayed anymore.

**Comment by null-null-null** [comment]
You could probably do something like this in the route:

```js
resetController: function(controller, isExiting, transition) {
  if (isExiting) {
    controller.set('keyboardActivated', false);
  } else {
    controller.set('keyboardActivated', true);
  }
}
```

Docs on [`resetController`](http://emberjs.com/api/classes/Ember.Route.html#method_resetController).

**Comment by ryanjm** [comment]
Thanks @null-null-null. For anyone else looking at this, I also had to add:

```
  setupController: function(controller, post) {
    this._super(controller, post);
    controller.set('keyboardActivated', true);
  },
```

Since `resetController` isn't called when coming back into the route.
