### ISSUE TITLE
Fastboot compatibility

### ISSUE THREAD

**Issue by clekstro** [null-null-null/ember-keyboard#46]
When attempting to install and run `ember-cli-fastboot`, I get the following error:
`ReferenceError: navigator is not defined`.

**Comment by null-null-null** [comment]
Thanks for the reminder. I had been putting off fastboot support until it left beta, but if there's need for it already, I can address this sooner. If you're interested, I could also point you the lines that need integration.

**Comment by null-null-null** [comment]
@clekstro I believe this issue should be resolved by `v2.1.3`. (I've got `ember-keyboard` working with a fastbooting version of the demo app.) Let me know if it resolves the problem for you.

**Comment by null-null-null** [comment]
This should be working now, but if not, feel free to reopen this one!
