### ISSUE TITLE
Getting "Could not find module `ember-get-config`..." error

### ISSUE THREAD

**Issue by djsegal** [null-null-null/ember-keyboard#47]
I think it might be related to a recent ember-get-config update

----------

``loader.js:219 Uncaught Error: Could not find module `ember-get-config` imported from `ember-keyboard/services/keyboard```

**Comment by null-null-null** [comment]
Removed `ember-get-config` from the deps in `v2.1.2`. Let me know if that fixes the problem you're having.

**Comment by null-null-null** [comment]
This should be working now. If it's not, feel free to reopen this one!
