### ISSUE TITLE
'Enter' key (all non-alphanumeric?) on input field do not fire

### ISSUE THREAD

**Issue by anijap** [null-null-null/ember-keyboard#49]
``` javascript
import Ember from 'ember';
import { EKMixin, EKOnFocusMixin, keyUp } from 'ember-keyboard';

export default Ember.TextField.extend(EKMixin, EKOnFocusMixin, {
    aFunction: Ember.on(keyUp('KeyS'), function() {
        console.log('`S` was pressed');
    }),
    aFunction2: Ember.on(keyUp('Enter'), function() {
        console.log('`Enter` was pressed');
    })
});
```

**KeyS** fires just fine but **Enter** does not.
A quick test also shows the **Shift** key does not fire. I suspect there are others. Perhaps all non-alphanumeric keys?

**Comment by null-null-null** [comment]
Good to know. I think I'll start a page in the documentation that just records all the keys we find that won't fire an event, and in which OSs they fail.

**Comment by anijap** [comment]
Isn't it fixable?
I can catch these keys without ember-keyboard just fine.

`{{input id="message-input" value=message autofocus="autofocus" key-press="handleKeyPress"}}`

```
import Ember from 'ember';

export default Ember.Component.extend({
	actions: {
		handleKeyPress() {
			if (window.event.keyCode === 13) {
                                console.log(this.get('message'));
			}
		}
	}
});
```

This is also what I imagine to be a relatively common use case: having a text field and expecting the enter key to kick off an action.

**Comment by null-null-null** [comment]
The question is, can you get that to work on `keyUp`, like in your TextField? Similarly, is the TextField still broken if you use `keyDown`?

**Comment by lolmaus** [comment]
Also ran into this, switched to `keyDown` which works fine.

**Comment by null-null-null** [comment]
Thanks for the reminder. Definitely need to get a list of key events that don't reach `ember-keyboard`.

**Comment by null-null-null** [comment]
Started compiling a list on the Usage page of the docs. In addition, I opened a new issue specifically for this [here](https://github.com/null-null-null/ember-keyboard/issues/56). Thanks again for reporting this @anijap  and @lolmaus.

**Comment by anijap** [comment]
Perhaps there could be a script that iterates through all the key events so that you could get a good idea of what is not working on Macs, Linux, etc?

**Comment by null-null-null** [comment]
That makes a lot of sense.

**Comment by lolmaus** [comment]
I guess you have to know what to test for... Like, we ran into this issue with text fields; who knows what other landmines await us out there?

**Comment by null-null-null** [comment]
@lolmaus Just to be clear, are you saying that you found events that will be swallowed when a text field is focused that are not swallowed otherwise?

**Comment by anijap** [comment]
Correct - when I ran into this it was only happening exclusively on text fields.

**Comment by null-null-null** [comment]
That's good to note. At the very least, we can run these tests both inside and outside of text fields. If other elements or states prove problematic, we can add those too.

**Comment by anijap** [comment]
Yep - at least it's a start :)
