### ISSUE TITLE
Unable to unit-test a component that uses ember-keyboard

### ISSUE THREAD

**Issue by lolmaus** [null-null-null/ember-keyboard#53]
Hi!

I would like to unit-test a component: `ember g component-test -u my-component`. The goal is to test methods and actions individually, without any context.

Even the basic test crashes with:

> Cannot call get with 'emberKeyboard.listeners' on an undefined object. 

Which seems come from to [these lines](https://github.com/null-null-null/ember-keyboard/blob/fefd4194c680a992a3afa0ea1f281830bc91725b/addon/services/keyboard.js#L38-L39):

```js
    const config = getOwner(this).resolveRegistration('config:environment');
    const listeners = get(config, 'emberKeyboard.listeners') || ['keyUp', 'keyDown', 'keyPress'];
```

How do I run unit tests in an ember-keyboard-driven component?

**Comment by null-null-null** [comment]
Thanks for the report! Should be fixed on `v2.1.5`. Let me know if that works for you.

**Comment by lolmaus** [comment]
Sorry, I no longer have access to that codebase. 

Please close if you believe it's fixed.

**Comment by null-null-null** [comment]
No worries. Thanks for reporting back.

**Comment by yjaspar** [comment]
Hi!

I just landed here after searching for unit-tests with ember and ember-keyboard.
I am trying to test my controller, but now that I added ember-keyboard to it, I'm getting that error:
`TypeError: Cannot read property 'register' of undefined`

The error seems to be located on [this](https://github.com/null-null-null/ember-keyboard/blob/master/addon/mixins/ember-keyboard.js#L14-L17):
```javascript
    // (...)
    keyboard: service(),

    init: function init() {
      get(this, 'keyboard').register(this);
    // (...)
```

**Comment by null-null-null** [comment]
@yjaspar Just to check, have you:

```js
moduleForComponent('my-component, 'Unit | Component | my component', {
  integration: true
});
```

or:

```js
moduleForComponent('my-component, 'Unit | Component | my component', {
  needs: ['service:keyboard']
});
```

**Comment by yjaspar** [comment]
I used to have the second one.
To make my tests pass I used the first one.
