### ISSUE TITLE
TypeError: (0 , _emberKeyboard.initialize) is not a function

### ISSUE THREAD

**Issue by et** [null-null-null/ember-keyboard#55]
As per the [testing page](http://null-null-null.github.io/ember-keyboard/#/testing).

```
import { initialize } from 'ember-keyboard';

moduleForComponent('my component', 'Integration | Component | my component', {
  integration: true,

  beforeEach() {
    initialize();
  }
});
```

throws an error:

`TypeError: (0 , _emberKeyboard.initialize) is not a function`

Given this commit, 477a1c1b09acc2aca8254cbd1cf0a5773012e077, it looks like the import is actually:
`import { initialize } from 'ember-keyboard/initializers/ember-keyboard-first-responder-inputs';`

Can you confirm this? If so, I can submit a PR to update the docs.

**Comment by null-null-null** [comment]
That could also work, but we should be able to just grab it directly off `ember-keyboard`. I'll look more into this soon and publish a fix. Thanks for bringing this to my attention, @et!

**Comment by null-null-null** [comment]
Hey @et, I'm having trouble replicating this. Would you mind letting me know which version of `ember-cli` and `ember-keyboard` you're using?

**Comment by et** [comment]
Hey @null-null-null, I was using:
```
ember-keyboard: 2.1.4
ember-cli: 2.8.0
```

using the latest release of `ember-keyboard: 2.1.9` works 👌 

Thanks and sorry for the noise.
