### ISSUE TITLE
Passthrough priority handling /  Explicit propagation

### ISSUE THREAD

**Issue by buschtoens** [null-null-null/ember-keyboard#63]
Firstly, thank you for this wonderful addon. I've been using it for over a year now and still love it. :heart: 

However, IMHO the current priority handling is a bit unpractical with big apps.

If component A has a higher priority than component B, then A swallows *all* shortcuts. Even if it does not intend to handle these or hasn't even set up listeners. `keyboardLaxPrirority` often isn't an option, since you need to actually overwrite some shortcuts of lower priority components.

I propose two things, that should be opt-in in order to stay backwards compatible:

1. ember-keyboard should check if the current component with the highest priority (A in the example described above) actually implements a listener for this shortcut. If not, the components with lower priority (B) should continue handling the event and so on and so forth.

2. If component A implements a listener and therefore propagation would stop at that point, the handler should be able to signal, that propagation should continue. I'm not sure, how to best implement this, but these here are some ideas:
    - `return` value:
      - `return true;`: continue propagation
      - `return false;` (or anything falsy): don't propagate
    - `return PROPAGATE;`: ember-keyboard could export a well known symbol that signals that propagation should continue. That way legacy code that may `return true` coincidentally won't trigger propagation.
    - `this.keyboardPropagate()`: `EKMixin` could add a method that, when called, signals that propagation should continue.
    - `propagate(event);`: ember-keyboard could export a function that accepts a keyboard event and signals that propagation should continue.

Are you :+1: on this? I would be happy to work on a PR.

**Comment by cbou** [comment]
Yeah I need this too!

**Comment by null-null-null** [comment]
Hi @buschtoens. I'm totally :+1: 

In terms of the preferred way for listeners to propagate, relying on return values could be problematic for an edge case: specifically, if somebody is ever manually calling these functions and using the return value. I don't see why that's an edge case we'd have to support, though. It would be easy enough for users to separate that out into two functions.

As for what to return, for the sake of future extensibility, I'm thinking we should return an object: `{ propagate: true }`.

What are your thoughts on that? Also, it's been a long time since you opened this issue. Are you still interested in making a PR?

**Comment by buschtoens** [comment]
> I don't see why that's an edge case we'd have to support, though. It would be easy enough for users to separate that out into two functions.

I second that. Should ember-keyboard complain loudly (assertion, warning) when an event handler returns an invalid object?

And yeah, I'm still very much interested in PR :blush:

**Comment by null-null-null** [comment]
Yes, a warning sounds like a wonderful idea! We're using [`ember-logger-test`](https://github.com/null-null-null/ember-logger-test) if you want to add a test around it.

**Comment by buschtoens** [comment]
Looking at the code I've just realized, that we can't use a return value, since [`trigger`](https://www.emberjs.com/api/ember/2.15/classes/Ember.Evented/methods/trigger?anchor=trigger) does not return the value of the listener, which makes sense, since you can have multiple listeners for one event.

Which highlights another problem: what should we do, if there are multiple listeners for a given event and they have different opinions about propagation. I know that's an edge case, but I would like to have mentioned it at least. :sweat_smile: 

I think we should pass a second argument. This could be a plain object with a [`stopPropagation()` method](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation). This closely mirrors the standard DOM API. It also means, that calling this method is irreversible, which makes sense IMO.

Using an object as the second argument also allows us to add possible future methods / information. I would recommend also recommend that the same object is re-used during a single propagation phase. This way users can add custom state to it, if they need to pass information from a higher priority component to a lower priority one.

**Comment by null-null-null** [comment]
I like that approach a lot. I feel like it has the potential to improve some of the things about `ember-keyboard` that have bothered me for a long time, too. So yes, let's do it like that!

**Comment by null-null-null** [comment]
(btw, thanks again for all the clean up you did this morning. it's really appreciated.)
